# Generated by Django 5.2.4 on 2025-09-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='descricao',
            new_name='nome',
        ),
    ]
