# Generated by Django 5.2.4 on 2025-09-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_colaborador', '0001_initial'),
        ('app_equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('emprestado', 'Emprestado'), ('em_uso', 'Em Uso'), ('fornecido', 'Fornecido'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='fornecido', max_length=10)),
                ('id_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_colaborador.colaborador')),
                ('id_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_equipamento.equipamento')),
            ],
        ),
    ]
