# Generated by Django 5.2.4 on 2025-09-13 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_colaborador', '0001_initial'),
        ('app_emprestimo', '0001_initial'),
        ('app_equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_entrega'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Prevista de Devolução'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Entrega'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Efetiva de Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='id_colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_colaborador.colaborador', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='id_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_equipamento.equipamento', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('emprestado', 'Emprestado'), ('em_uso', 'Em Uso'), ('fornecido', 'Fornecido'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='fornecido', max_length=10, verbose_name='Status'),
        ),
    ]
