# Generated by Django 5.2.6 on 2025-09-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimo', '0002_alter_emprestimo_options_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data revista de Devolução'),
        ),
    ]
