# Generated by Django 5.2.4 on 2025-09-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimo', '0003_alter_emprestimo_data_devolucao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={},
        ),
    ]
