# Generated by Django 5.2.4 on 2025-09-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimo', '0004_alter_emprestimo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Prevista'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('emprestado', 'Emprestado'), ('fornecido', 'Fornecido'), ('devolvido', 'Devolvido'), ('danificado', 'Danificado'), ('perdido', 'Perdido')], default='fornecido', max_length=10, verbose_name='Status'),
        ),
    ]
