# Generated by Django 5.2.4 on 2025-10-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimo', '0005_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_entrega'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
    ]
