# Generated by Django 5.2.4 on 2025-08-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_epi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='password',
        ),
    ]
